{{- if eq .Values.webapp.kind "deployment" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ default (include "app.name" .) .Values.webapp.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.webapp.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "app.appName" . }}
  template:
    metadata:
      labels:
        app: {{ include "app.appName" . }}
{{- if or (.Values.prometheus.create) (.Values.webapp.pod.annotations) }}
      annotations:
{{- if .Values.prometheus.create }}
        prometheus.io/scrape: "true"
        prometheus.io/port: "{{ .Values.prometheus.port }}"
{{- end }}
{{- if .Values.webapp.pod.annotations }}
{{ toYaml .Values.webapp.pod.annotations | indent 8 }}
{{- end }}
{{- end }}
    spec:
{{- if .Values.webapp.volumes }}
      volumes:
{{ toYaml .Values.webapp.volumes | indent 6 }}
{{- end }}
      serviceAccountName: {{ include "app.serviceAccountName" . }}
      hostNetwork: {{ .Values.webapp.hostNetwork }}
      containers:
{{- if .Values.frontend.create }}
      - image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
        name: frontend
        imagePullPolicy: "{{ .Values.frontend.image.pullPolicy }}"
        ports:
        - name: frontend
          containerPort: {{ .Values.frontend.port }}
{{- end }}
      - image: "{{ .Values.webapp.image.repository }}:{{ .Values.webapp.image.tag }}"
        name: {{ include "app.name" . }}
        imagePullPolicy: "{{ .Values.webapp.image.pullPolicy }}"
        ports:
        - name: http
          containerPort: {{ .Values.webapp.port }}
{{ if .Values.webapp.customPorts }}
{{ toYaml .Values.webapp.customPorts | indent 8 }}
{{ end }}
{{- if .Values.prometheus.create }}
        - name: prometheus
          containerPort: {{ .Values.prometheus.port }}
{{- end }}
        resources:
{{ toYaml .Values.webapp.resources | indent 10 }}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
{{- if .Values.webapp.volumeMounts }}
        volumeMounts:
{{ toYaml .Values.webapp.volumeMounts | indent 8 }}
{{- end }}
        env:
        - name: APP_PORT
          value: "{{ .Values.webapp.port }}"
        - name: PROMETHEUS_PORT
          value: "{{ .Values.prometheus.port }}"
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
{{- end }}
