{{- if .Values.service.create }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "app.serviceName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
{{- if .Values.service.annotations }}
  annotations:
{{ toYaml .Values.service.annotations | indent 4 }}
{{- end }}
spec:
{{- if or (eq .Values.service.type "LoadBalancer") (eq .Values.service.type "NodePort") }}
  {{- if .Values.service.externalTrafficPolicy }}
  externalTrafficPolicy: {{ .Values.service.externalTrafficPolicy }}
  {{- end }}
{{- end }}
{{- if eq .Values.service.type "LoadBalancer" }}
  {{- if .Values.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
  {{- end }}
  {{- if .Values.service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
{{ toYaml .Values.service.loadBalancerSourceRanges | indent 4 }}
  {{- end }}
{{- end }}
  type: {{ .Values.service.type }}
  ports:
{{- if .Values.service.customPorts }}
{{ toYaml .Values.service.customPorts | indent 2 }}
{{ end }}
{{- if .Values.service.httpPort.enable }}
  - port: {{ .Values.service.httpPort.port }}
    targetPort: {{ .Values.service.httpPort.targetPort }}
    protocol: TCP
    name: http
{{- end }}
{{- if .Values.service.frontend.enable }}
  - port: {{ .Values.service.frontend.port }}
    targetPort: {{ .Values.service.frontend.targetPort }}
    protocol: TCP
    name: frontend
{{- end }}
{{- if .Values.service.prometheus.enable }}
  - port: {{ .Values.service.prometheus.port }}
    targetPort: {{ .Values.service.prometheus.targetPort }}
    protocol: TCP
    name: prometheus
{{- end }}
  selector:
    app:  {{ include "app.appName" . }}
  {{- if .Values.service.externalIPs }}
  externalIPs:
{{ toYaml .Values.service.externalIPs | indent 4 }}
  {{- end }}
{{- end }}
