{{- if .Values.rbac.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "app.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
{{- if .Values.webapp.serviceAccount.imagePullSecretName }}
imagePullSecrets:
- name: {{ .Values.webapp.serviceAccount.imagePullSecretName }}
{{- end }}
{{- if and (.Values.webapp.serviceAccount.imagePullSecrets) (not .Values.webapp.serviceAccount.imagePullSecretName) }}
imagePullSecrets:
{{ toYaml .Values.webapp.serviceAccount.imagePullSecrets }}
{{- end }}
{{- end }}
